name: CI

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        name: test app
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            - run: bun install
            - run: bun test
